spring:
  config:
    import: optional:file:../.env[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${BACKEND_PORT}
  address: ${BACKEND_BIND_ADDRESS:127.0.0.1}

fatcatkill:
  debug-actions: ${ENABLE_DEBUG_ACTIONS:false}
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173}
